version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"

mkdocs:
  configuration: mkdocs.yml

python:
  install:
    - requirements: docs/readthedocs/requirements.txt

sphinx:
  fail_on_warning: true