"""Small, dependency-free localization layer for the server-rendered UI.

English remains the source language.  The browser receives the selected catalog
so Alpine-rendered and other client-side messages use the same translations as
the initial HTML response.
"""

from typing import Dict, Optional

from fastapi import Request

SUPPORTED_LOCALES = ("en", "de")
LOCALE_COOKIE = "dmarq_locale"


DE_TRANSLATIONS: Dict[str, str] = {
    # Application shell and shared actions
    "Dashboard": "Übersicht",
    "Domains": "Domains",
    "Reports": "Berichte",
    "Mail Sources": "Mailquellen",
    "Members": "Mitglieder",
    "More": "Mehr",
    "More tools": "Weitere Werkzeuge",
    "Specialized tools": "Spezialwerkzeuge",
    "Settings": "Einstellungen",
    "Profile & Security": "Profil & Sicherheit",
    "Advanced tools": "Erweiterte Werkzeuge",
    "Forensic reports": "Forensische Berichte",
    "Forensic Reports": "Forensische Berichte",
    "TLS reports": "TLS-Berichte",
    "Setup assistant": "Einrichtungsassistent",
    "Release": "Version",
    "Sign out": "Abmelden",
    "Sign in": "Anmelden",
    "Workspace": "Arbeitsbereich",
    "Show release notes": "Versionshinweise anzeigen",
    "Current release": "Aktuelle Version",
    "What's changed": "Änderungen",
    "Full changelog": "Vollständiges Änderungsprotokoll",
    "Close": "Schließen",
    "Cancel": "Abbrechen",
    "Save": "Speichern",
    "Delete": "Löschen",
    "Edit": "Bearbeiten",
    "Add": "Hinzufügen",
    "Back": "Zurück",
    "Open": "Öffnen",
    "Reload": "Neu laden",
    "Refresh": "Aktualisieren",
    "Retry": "Erneut versuchen",
    "Loading…": "Wird geladen…",
    "Never": "Nie",
    "None": "Keine",
    "Status": "Status",
    "Details": "Details",
    "Description": "Beschreibung",
    "Advanced": "Erweitert",
    "General": "Allgemein",
    "Language": "Sprache",
    "English": "Englisch",
    "German": "Deutsch",
    "Choose the language used for navigation, guidance, dates, and numbers in this browser.": "Wähle die Sprache für Navigation, Hinweise, Datumsangaben und Zahlen in diesem Browser.",
    "Your explicit choice is kept in this browser and takes precedence over the instance default.": "Deine ausdrückliche Auswahl wird in diesem Browser gespeichert und hat Vorrang vor dem Instanzstandard.",
    "Account": "Konto",
    "Name": "Name",
    "Domain": "Domain",
    "Date": "Datum",
    "Owner": "Verantwortlich",
    "Priority": "Priorität",
    "View details": "Details anzeigen",
    "More actions": "Weitere Aktionen",
    "No action": "Keine Aktion",
    "Unknown": "Unbekannt",
    "Loading": "Wird geladen",
    "Pass": "Bestanden",
    "Fail": "Fehlgeschlagen",
    "Clean": "Unauffällig",
    "Listed": "Gelistet",
    "Unchecked": "Nicht geprüft",
    "Recent": "Kürzlich",
    "All time": "Gesamter Zeitraum",
    "Last 7 days": "Letzte 7 Tage",
    "Last 14 days": "Letzte 14 Tage",
    "Last 30 days": "Letzte 30 Tage",
    "Last 90 days": "Letzte 90 Tage",
    "All Domains": "Alle Domains",
    "Date Range": "Zeitraum",
    # First-run dashboard
    "WELCOME TO DMARQ": "WILLKOMMEN BEI DMARQ",
    "Start by connecting your report mailbox": "Verbinde zuerst dein Berichts-Postfach",
    "DMARQ needs aggregate reports before it can identify senders, measure authentication, or recommend DNS changes.": "DMARQ benötigt aggregierte Berichte, bevor Absender erkannt, Authentifizierung gemessen oder DNS-Änderungen empfohlen werden können.",
    "Connect report mailbox": "Berichts-Postfach verbinden",
    "Other import options": "Weitere Importmöglichkeiten",
    "Report Intake Status": "Status des Berichtseingangs",
    "Trigger Poll Now": "Postfach jetzt prüfen",
    "No enabled sources": "Keine aktive Quelle",
    "Last Check:": "Letzte Prüfung:",
    "Sources:": "Quellen:",
    "Attention:": "Achtung:",
    "Open Mail Sources": "Mailquellen öffnen",
    "Loading configured mail sources...": "Konfigurierte Mailquellen werden geladen…",
    "No enabled mail sources configured": "Keine aktive Mailquelle konfiguriert",
    "Add or review domains": "Domains hinzufügen oder prüfen",
    "Already have a DMARC XML or ZIP file? Import it once instead of connecting a mailbox.": "Liegt bereits eine DMARC-XML- oder ZIP-Datei vor? Importiere sie einmalig, statt ein Postfach zu verbinden.",
    "Import report file": "Berichtsdatei importieren",
    "Loading dashboard data": "Übersichtsdaten werden geladen",
    "Dashboard could not be loaded": "Die Übersicht konnte nicht geladen werden",
    "Dashboard refresh failed": "Die Übersicht konnte nicht aktualisiert werden",
    "Open domains": "Domains öffnen",
    "Open reports": "Berichte öffnen",
    "Portfolio health": "Portfolio-Zustand",
    "Analytics and evidence": "Analysen und Nachweise",
    "Remediation Loop": "Behebungsprozess",
    "Current fix queue": "Aktuelle Aufgabenliste",
    "Open remediation queue": "Behebungsaufgaben öffnen",
    "No active remediation work queued": "Keine aktiven Behebungsaufgaben",
    "Next action:": "Nächste Aktion:",
    "Next safe action:": "Nächste sichere Aktion:",
    "Done when": "Erledigt, wenn",
    "Fresh evidence": "Aktuelle Nachweise",
    "Need fresh evidence": "Aktuelle Nachweise erforderlich",
    "Needs approval": "Freigabe erforderlich",
    "Resolved": "Erledigt",
    "Investigate": "Untersuchen",
    "Manual action": "Manuelle Aktion",
    "Emails": "E-Mails",
    "Enforcement Rate": "Durchsetzungsrate",
    "DNS Record Health": "DNS-Zustand",
    "DMARC Compliance Rate": "DMARC-Konformitätsrate",
    # Domains
    "Domain Management": "Domainverwaltung",
    "Add monitored domain": "Überwachte Domain hinzufügen",
    "Edit monitored domain": "Überwachte Domain bearbeiten",
    "Loading monitored domains...": "Überwachte Domains werden geladen…",
    "No domains found. Add a domain to get started.": "Keine Domains gefunden. Füge eine Domain hinzu, um zu beginnen.",
    "All monitored domains are currently hidden because no reports or mail volume have been observed yet.": "Alle überwachten Domains sind ausgeblendet, weil noch keine Berichte oder E-Mail-Mengen vorliegen.",
    "Track DNS health and future DMARC reports before the first report arrives.": "Überwache DNS-Zustand und künftige DMARC-Berichte bereits vor dem ersten Bericht.",
    "DKIM selectors": "DKIM-Selektoren",
    "DMARC report mailbox override": "Abweichendes DMARC-Berichts-Postfach",
    "Sending Sources": "Versandquellen",
    "Domain detail": "Domain-Details",
    "Domain health grade": "Domain-Bewertung",
    "Current health score": "Aktueller Zustandswert",
    "Next remediation": "Nächste Behebung",
    "Action plan": "Aktionsplan",
    "Authentication review": "Authentifizierungsprüfung",
    "Current failures:": "Aktuelle Fehler:",
    "Current passes:": "Aktuell bestanden:",
    "Failed emails": "Fehlgeschlagene E-Mails",
    "First seen": "Erstmals gesehen",
    "Last seen": "Zuletzt gesehen",
    "Last sent": "Zuletzt gesendet",
    "Captured during processing": "Bei der Verarbeitung erfasst",
    "Source intelligence": "Absenderinformationen",
    "Country unknown": "Land unbekannt",
    "Geo unavailable": "Geodaten nicht verfügbar",
    "PTR unavailable": "PTR nicht verfügbar",
    "Unknown sender": "Unbekannter Absender",
    "Observed messages": "Beobachtete Nachrichten",
    "DMARC failure rate": "DMARC-Fehlerrate",
    "Reputation review": "Reputationsprüfung",
    "Clean reputation": "Unauffällige Reputation",
    "Recalculate reputation": "Reputation neu berechnen",
    "Show IP evidence": "IP-Nachweise anzeigen",
    "Open in Cloudflare Radar": "In Cloudflare Radar öffnen",
    "Recommended next steps": "Empfohlene nächste Schritte",
    "Raw record evidence": "Unverarbeitete Nachweise",
    # Reports
    "DMARC Reports": "DMARC-Berichte",
    "Aggregate evidence": "Aggregierte Nachweise",
    "Reporter": "Berichtanbieter",
    "Messages": "Nachrichten",
    "Loading reports...": "Berichte werden geladen…",
    "Checking report index...": "Berichtsindex wird geprüft…",
    "Reports unavailable": "Berichte nicht verfügbar",
    "Retry loading reports": "Berichte erneut laden",
    "Trigger report refresh": "Berichte aktualisieren",
    "This should only take a moment. If it stays empty, open Mail Sources and check the last import.": "Dies sollte nur einen Moment dauern. Bleibt die Ansicht leer, öffne die Mailquellen und prüfe den letzten Import.",
    "Aggregate report": "Aggregierter Bericht",
    "Report ID": "Berichts-ID",
    "Organization": "Organisation",
    "Period Start": "Zeitraum von",
    "Period End": "Zeitraum bis",
    "Messages covered": "Erfasste Nachrichten",
    "Authentication rate": "Authentifizierungsrate",
    "DMARC aligned": "DMARC-konform",
    "All records": "Alle Einträge",
    "No records in this report": "Dieser Bericht enthält keine Einträge",
    "No records match this reputation view.": "Keine Einträge entsprechen dieser Reputationsansicht.",
    "Expand individual IP, authentication, reputation, and policy results.": "Blende einzelne IP-, Authentifizierungs-, Reputations- und Richtlinienergebnisse ein.",
    # Mail sources
    "Add Mail Source": "Mailquelle hinzufügen",
    "Edit settings": "Einstellungen bearbeiten",
    "Test Connection": "Verbindung testen",
    "Enable this mail source": "Diese Mailquelle aktivieren",
    "Polling Interval (minutes)": "Prüfintervall (Minuten)",
    "Historical import": "Historischer Import",
    "Backfill Mail Source": "Mailquelle rückwirkend importieren",
    "Backfill date range": "Zeitraum des rückwirkenden Imports",
    "Days to search": "Zu durchsuchende Tage",
    "Run first backfill": "Ersten rückwirkenden Import starten",
    "Import history": "Importverlauf",
    "No import attempts recorded yet.": "Noch keine Importversuche erfasst.",
    "No backfill has been run for this account.": "Für dieses Konto wurde noch kein rückwirkender Import ausgeführt.",
    "Last mailbox check": "Letzte Postfachprüfung",
    "Connect Gmail": "Gmail verbinden",
    "Connect Microsoft 365": "Microsoft 365 verbinden",
    "Authentication": "Authentifizierung",
    "Password": "Passwort",
    "Leave blank to keep the saved password": "Leer lassen, um das gespeicherte Passwort beizubehalten",
    "Save the source first, then edit it to test mailbox access and load folders.": "Speichere die Quelle zuerst. Bearbeite sie anschließend, um den Postfachzugriff zu testen und Ordner zu laden.",
    "Delete Mail Source": "Mailquelle löschen",
    "Delete account": "Konto löschen",
    "Test application access": "Anwendungszugriff testen",
    "Application access": "Anwendungszugriff",
    "Mail.Read application permission": "Anwendungsberechtigung Mail.Read",
    "Limit mailbox access in Exchange Online": "Postfachzugriff in Exchange Online einschränken",
    "Duplicates": "Duplikate",
    "Errors": "Fehler",
    "Recognized": "Erkannt",
    "Ignored": "Ignoriert",
    # Settings
    "Recommended setup": "Empfohlene Einrichtung",
    "Finish the next safe setup step": "Führe den nächsten sicheren Einrichtungsschritt aus",
    "Connect the mailbox that receives DMARC reports first. Add domains and DNS automation only after report intake is working.": "Verbinde zuerst das Postfach, das DMARC-Berichte empfängt. Füge Domains und DNS-Automatisierung erst hinzu, wenn der Berichtseingang funktioniert.",
    "Connect reports": "Berichte verbinden",
    "Add domains": "Domains hinzufügen",
    "Review DNS": "DNS prüfen",
    "Choose notifications": "Benachrichtigungen auswählen",
    "Setup": "Einrichtung",
    "DMARC defaults": "DMARC-Standards",
    "Domains and DNS": "Domains und DNS",
    "Notifications": "Benachrichtigungen",
    "Report mailbox": "Berichts-Postfach",
    "DNS resolver": "DNS-Auflösung",
    "Sender imports": "Absenderimporte",
    "Privacy": "Datenschutz",
    "Webhooks": "Webhooks",
    "AI and agents": "KI und Agenten",
    "Account diagnostics": "Kontodiagnose",
    "Application Name": "Anwendungsname",
    "Base URL": "Basis-URL",
    "Reports per page": "Berichte pro Seite",
    "Session lifetime (minutes)": "Sitzungsdauer (Minuten)",
    "Save General Settings": "Allgemeine Einstellungen speichern",
    "DNS Resolver": "DNS-Auflösung",
    "Resolver ready": "DNS-Auflösung bereit",
    "Using safe DNS fallback": "Sichere DNS-Ausweichlösung wird verwendet",
    "DNS Provider Connectors": "DNS-Anbieter verbinden",
    "Account and access diagnostics": "Konto- und Zugriffsdiagnose",
    "Loading account readiness...": "Kontobereitschaft wird geladen…",
    "Aggregate report mailbox": "Postfach für aggregierte Berichte",
    "Daily summary": "Tägliche Zusammenfassung",
    "Weekly summary": "Wöchentliche Zusammenfassung",
    "Enable notifications": "Benachrichtigungen aktivieren",
    "Save Settings": "Einstellungen speichern",
    "Settings saved successfully": "Einstellungen wurden gespeichert",
    "Failed to save settings": "Einstellungen konnten nicht gespeichert werden",
    # Empty/error/success states
    "No data available": "Keine Daten verfügbar",
    "No results found": "Keine Ergebnisse gefunden",
    "Something went wrong": "Etwas ist schiefgelaufen",
    "Try again": "Erneut versuchen",
    "Connection successful": "Verbindung erfolgreich",
    "Connection failed": "Verbindung fehlgeschlagen",
    "Saving…": "Wird gespeichert…",
    "Saved": "Gespeichert",
    # Dashboard and remediation details
    "DMARQ is checking domains, report volume, DNS health, and sender signals.": "DMARQ prüft Domains, Berichtsvolumen, DNS-Zustand und Absendersignale.",
    "No immediate remediation action": "Keine sofortige Behebung erforderlich",
    "Keep report intake running and review new sender or DNS changes when they appear.": "Lasse den Berichtseingang weiterlaufen und prüfe neue Absender- oder DNS-Änderungen, sobald sie auftreten.",
    "Report-backed domains only": "Nur Domains mit Berichten",
    "View domains": "Domains anzeigen",
    "No report-backed domain selected": "Keine Domain mit Berichten ausgewählt",
    "Policy: unknown": "Richtlinie: unbekannt",
    "No sending source data available": "Keine Daten zu Versandquellen verfügbar",
    "No failures": "Keine Fehler",
    "Recent source and compliance changes": "Aktuelle Änderungen bei Absendern und Konformität",
    "Review evidence": "Nachweise prüfen",
    "No major sender or compliance changes detected.": "Keine wesentlichen Änderungen bei Absendern oder Konformität erkannt.",
    "Domain Compliance": "Domain-Konformität",
    "All-time imported evidence. Open a domain for the complete remediation plan.": "Importierte Nachweise über den gesamten Zeitraum. Öffne eine Domain für den vollständigen Behebungsplan.",
    "Domain health breakdown": "Verteilung des Domain-Zustands",
    "Traffic-weighted health": "Nach Volumen gewichteter Zustand",
    "No prior score": "Kein vorheriger Wert",
    "Additional fixes after the primary next action above.": "Weitere Behebungen nach der oben genannten nächsten Hauptaktion.",
    "No additional remediation actions. Keep monitoring reports and DNS drift.": "Keine weiteren Behebungsaktionen. Überwache weiterhin Berichte und DNS-Abweichungen.",
    "Domain Grades": "Domain-Bewertungen",
    "Last 24 hours": "Letzte 24 Stunden",
    "Last 48 hours": "Letzte 48 Stunden",
    "Week to date": "Laufende Woche",
    "Month to date": "Laufender Monat",
    "Advanced remediation workflow": "Erweiterter Behebungsprozess",
    "Keep importing reports and monitoring DNS.": "Importiere weiterhin Berichte und überwache DNS.",
    "Open domain worklist": "Domain-Aufgaben öffnen",
    "Queue controls and operational metrics": "Aufgabensteuerung und Betriebskennzahlen",
    "Keep the remediation loop open until every closure gate is represented.": "Lasse den Behebungsprozess offen, bis alle Abschlusskriterien erfüllt sind.",
    "Resolved items no longer observed": "Erledigte Punkte werden nicht mehr beobachtet",
    "DNS or policy changes to review": "Zu prüfende DNS- oder Richtlinienänderungen",
    "waiting for explicit approval": "wartet auf ausdrückliche Freigabe",
    "Tasks for mail or DNS owners": "Aufgaben für Mail- oder DNS-Verantwortliche",
    "Sender or report evidence to confirm": "Zu bestätigende Absender- oder Berichtsnachweise",
    "Repair previews ready": "Behebungsvorschauen bereit",
    "Provider-backed proposals ready for review": "Anbietergestützte Vorschläge zur Prüfung bereit",
    "Notifications ready": "Benachrichtigungen bereit",
    "Missing provider values or prerequisites": "Fehlende Anbieterwerte oder Voraussetzungen",
    "Preview ready": "Vorschau bereit",
    "Ready to notify": "Benachrichtigung bereit",
    "Report evidence": "Berichtsnachweis",
    "Stale evidence": "Veralteter Nachweis",
    "Choose another queue view or refresh after new evidence is available.": "Wähle eine andere Aufgabenansicht oder aktualisiere, sobald neue Nachweise vorliegen.",
    "Show all remediation cards": "Alle Behebungsaufgaben anzeigen",
    "Welcome to DMARQ": "Willkommen bei DMARQ",
    "Upload a report file": "Berichtsdatei hochladen",
    "Change the evidence window": "Nachweiszeitraum ändern",
    "Next": "Weiter",
    # Domain workbench
    "Add Domain": "Domain hinzufügen",
    "DMARC Status": "DMARC-Status",
    "SPF Status": "SPF-Status",
    "DKIM Status": "DKIM-Status",
    "Optional. Leave empty to use the aggregate report mailbox from Settings or dmarc@domain.": "Optional. Leer lassen, um das Postfach für aggregierte Berichte aus den Einstellungen oder dmarc@domain zu verwenden.",
    "Add domain": "Domain hinzufügen",
    "Save changes": "Änderungen speichern",
    "Check DNS records": "DNS-Einträge prüfen",
    "Delete domain": "Domain löschen",
    "Loading next remediation...": "Nächste Behebung wird geladen…",
    "Domain ownership and DNS write safety": "Domaininhaberschaft und sichere DNS-Änderungen",
    "Domain Ownership": "Domaininhaberschaft",
    "Proof status for DNS writes and one-click repair; report ingestion does not require this gate.": "Nachweisstatus für DNS-Änderungen und Ein-Klick-Behebung; der Berichtsimport benötigt dieses Kriterium nicht.",
    "Check ownership": "Inhaberschaft prüfen",
    "Daily DMARC volume, pass rate, and failure rate": "Tägliches DMARC-Volumen sowie Erfolgs- und Fehlerrate",
    "Advanced remediation and posture": "Erweiterte Behebung und Sicherheitslage",
    "Evidence-linked coverage, drift, and operator playbooks": "Nachweisbasierte Abdeckung, Abweichungen und Betriebsabläufe",
    "Prioritized fixes with evidence, prerequisites, and approval status.": "Priorisierte Behebungen mit Nachweisen, Voraussetzungen und Freigabestatus.",
    "approval-ready": "freigabebereit",
    "preview ready": "Vorschau bereit",
    "need evidence": "Nachweis erforderlich",
    "ready to notify": "Benachrichtigung bereit",
    "Loading remediation queue...": "Behebungsaufgaben werden geladen…",
    "Filter and sort queue": "Aufgaben filtern und sortieren",
    "Needs evidence": "Nachweis erforderlich",
    "Health history": "Zustandsverlauf",
    "Health Score Trend": "Verlauf des Zustandswerts",
    "Score movement, top drivers, and audit-ready evidence for this domain": "Wertentwicklung, wichtigste Einflussfaktoren und revisionsfähige Nachweise für diese Domain",
    "Export evidence": "Nachweise exportieren",
    "No previous score": "Kein vorheriger Wert",
    "No snapshot": "Keine Momentaufnahme",
    "No active score drivers in the latest snapshot.": "Keine aktiven Einflussfaktoren in der neuesten Momentaufnahme.",
    "Evidence window": "Nachweiszeitraum",
    "Export includes aggregate score evidence only; forensic message bodies are not included.": "Der Export enthält nur aggregierte Bewertungsnachweise; forensische Nachrichteninhalte sind nicht enthalten.",
    "Source platform": "Quellplattform",
    "Source": "Quelle",
    "DNS and authentication": "DNS und Authentifizierung",
    "DNS Records": "DNS-Einträge",
    "Email authentication DNS records for this domain": "DNS-Einträge zur E-Mail-Authentifizierung dieser Domain",
    "Looking up authoritative nameservers and authentication records.": "Autoritative Nameserver und Authentifizierungseinträge werden abgefragt.",
    "Checking provider connection and safe DNS repair options.": "Anbieterverbindung und sichere DNS-Behebungsmöglichkeiten werden geprüft.",
    "No live writes": "Keine direkten Änderungen",
    "Wait for DNS checks to complete.": "Warte, bis die DNS-Prüfungen abgeschlossen sind.",
    "No _mta-sts TXT record found": "Kein _mta-sts-TXT-Eintrag gefunden",
    "No BIMI TXT record found at default._bimi": "Kein BIMI-TXT-Eintrag unter default._bimi gefunden",
    "No manually configured selectors yet.": "Noch keine manuell konfigurierten Selektoren.",
    "Selector evidence": "Selektornachweise",
    "No DNS lint findings.": "Keine DNS-Prüffunde.",
    "Work through DMARC, SPF, and DKIM in this order before tightening enforcement.": "Bearbeite DMARC, SPF und DKIM in dieser Reihenfolge, bevor die Durchsetzung verschärft wird.",
    "Optional transport and branding records": "Optionale Transport- und Markeneinträge",
    "Source Intelligence": "Absenderinformationen",
    "Regions, networks, and unusual sending-source changes for this domain": "Regionen, Netzwerke und ungewöhnliche Änderungen der Versandquellen dieser Domain",
    "New sending source": "Neue Versandquelle",
    "Confirm ownership before authorizing this source in DNS.": "Bestätige die Verantwortlichkeit, bevor diese Quelle im DNS autorisiert wird.",
    "IP addresses and servers sending email as this domain": "IP-Adressen und Server, die E-Mails für diese Domain senden",
    "Loading sending sources...": "Versandquellen werden geladen…",
    "Latest DMARC reports received for this domain": "Neueste DMARC-Berichte für diese Domain",
    "View": "Anzeigen",
    # Settings and mailbox details
    "Configured Accounts": "Konfigurierte Konten",
    "Import new reports, review mailbox health, or run a historical backfill.": "Importiere neue Berichte, prüfe den Postfachzustand oder starte einen historischen Import.",
    "No mail sources configured yet. Click": "Noch keine Mailquellen konfiguriert. Klicke",
    "How often to check for new reports (min 15 min)": "Intervall für neue Berichte (mindestens 15 Minuten)",
    "Queues a resumable mailbox search. Progress appears in the Backfill column.": "Startet eine fortsetzbare Postfachsuche. Der Fortschritt erscheint in der Spalte für historische Importe.",
    "Basic application settings": "Grundlegende Anwendungseinstellungen",
    "Display name shown in the navigation bar and page titles": "Anzeigename in Navigation und Seitentiteln",
    "Public URL used in OAuth2 redirect URIs and email links": "Öffentliche URL für OAuth2-Weiterleitungen und E-Mail-Links",
    "DMARC Policy Defaults": "DMARC-Richtlinienstandards",
    "Default values applied when adding a new domain": "Standardwerte für neu hinzugefügte Domains",
    "Default Policy": "Standardrichtlinie",
    "Quarantine (send to spam)": "Quarantäne (als Spam behandeln)",
    "TLS report mailbox": "Postfach für TLS-Berichte",
    "Choose how DMARQ resolves DNS records for domain lookups": "Lege fest, wie DMARQ DNS-Einträge für Domainabfragen auflöst",
    "Provider Domain Discovery": "Domains beim Anbieter erkennen",
    "Find DNS zones and import them into DMARQ before reports arrive.": "Finde DNS-Zonen und importiere sie in DMARQ, bevor Berichte eintreffen.",
    "Provider setup docs": "Dokumentation zur Anbietereinrichtung",
    "Advanced privacy settings": "Erweiterte Datenschutzeinstellungen",
    "Control privacy for forensic report metadata": "Datenschutz für Metadaten forensischer Berichte steuern",
    "No alert history yet.": "Noch kein Alarmverlauf.",
    "No configuration changes recorded yet.": "Noch keine Konfigurationsänderungen erfasst.",
    "Check Alerts": "Alarme prüfen",
    "Advanced webhook delivery": "Erweiterte Webhook-Zustellung",
    "Signed event fan-out and delivery history": "Signierte Ereignisverteilung und Zustellverlauf",
    "No outbound webhooks configured yet.": "Noch keine ausgehenden Webhooks konfiguriert.",
    "No webhook deliveries recorded yet.": "Noch keine Webhook-Zustellungen erfasst.",
    "Advanced AI and agent automation": "Erweiterte KI- und Agentenautomatisierung",
    "Opt-in model and MCP controls": "Optionale Modell- und MCP-Steuerung",
    "AI and Agent Automation": "KI- und Agentenautomatisierung",
    "Use deterministic local remediation templates. No token or network call.": "Verwende deterministische lokale Behebungsvorlagen. Kein Token und kein Netzwerkaufruf.",
}


# The provider demo predates the common English source-language convention.
# Keep its existing copy stable while making the English product mode complete.
EN_TRANSLATIONS: Dict[str, str] = {
    "Abbrechen": "Cancel",
    "Abrechnung und Plan gelten für dieses Kundenkonto.": "Billing and plan apply to this customer account.",
    "Abrechnungsmodell": "Billing model",
    "Account erstellen": "Create account",
    "Account öffnen": "Open account",
    "Account-, Import-, Billing- und Support-Ereignisse.": "Account, import, billing, and support events.",
    "Account-Kontakt": "Account contact",
    "Aktivitätsprotokoll": "Activity log",
    "Aktuell": "Current",
    "Alle anzeigen": "Show all",
    "Als Kunde öffnen": "Open as customer",
    "Ansicht als": "Viewing as",
    "Authentifizierung, Policy und Berichtseingang im Account.": "Authentication, policy, and report intake for this account.",
    "Benutzer": "Users",
    "Benutzer einladen": "Invite user",
    "Billing bearbeiten": "Edit billing",
    "Billing speichern": "Save billing",
    "Domains / Benutzer": "Domains / users",
    "Erneut versuchen": "Try again",
    "Filter zurücksetzen oder ein neues Kundenkonto anlegen.": "Reset the filters or create a new customer account.",
    "Firmenname": "Company name",
    "Grund": "Reason",
    "Handlungsbedarf": "Needs attention",
    "Handlungsbedarf zuerst": "Needs attention first",
    "Interaktive Demo:": "Interactive demo:",
    "Keine passenden Accounts": "No matching accounts",
    "Kontakt": "Contact",
    "Kundenansicht öffnen": "Open customer view",
    "Kundenkonten": "Customer accounts",
    "Kundenkonten verwalten": "Manage customer accounts",
    "Kundenkonto anlegen": "Create customer account",
    "Letzter Report": "Latest report",
    "Mails · 30 T.": "Messages · 30 d.",
    "Mails · 30 Tage": "Messages · 30 days",
    "Mailvolumen": "Mail volume",
    "Mailvolumen · 30 Tage": "Mail volume · 30 days",
    "Monatlich": "Monthly",
    "Monatlicher Betrag": "Monthly amount",
    "Monatlicher Umsatz": "Monthly revenue",
    "Nach Risiko sortiert. Der nächste sinnvolle Schritt bleibt pro Account sichtbar.": "Sorted by risk. The next useful action stays visible for every account.",
    "Neues Kundenkonto": "New customer account",
    "Nächste sinnvolle Aktion": "Next useful action",
    "Offene Hinweise": "Open findings",
    "Organisationsinhaber": "Organization owner",
    "Primäre Domain": "Primary domain",
    "Protokollierter Support-Zugriff": "Audited support access",
    "Provider-Daten werden geladen...": "Loading provider data...",
    "Provider-Rechnung": "Provider invoice",
    "Provider-Verwaltung": "Provider management",
    "Provider-Verwaltung konnte nicht geladen werden": "Provider management could not be loaded",
    "Rechnungsempfänger": "Invoice recipient",
    "Rechnungsreferenz": "Invoice reference",
    "Schließen": "Close",
    "Sicherheitsrahmen": "Security controls",
    "Single-user-Demo": "Single-user demo",
    "Sortierung": "Sort order",
    "Suche": "Search",
    "Support-Ansicht": "Support view",
    "Support-Sitzung starten": "Start support session",
    "Testphase": "Trial",
    "Umsatz": "Revenue",
    "Vertragsrechnung": "Contract invoice",
    "Zuletzt aktiv": "Last active",
    "kritisch, auffällig oder überfällig": "critical, notable, or overdue",
    "volumengewichtet": "volume weighted",
    "Überfällig": "Overdue",
    "Kundenkonto": "Customer account",
    "Nur Lesen": "Read only",
    "Rollenberechtigungen aktiv": "Role permissions active",
    "Nicht konfiguriert": "Not configured",
    "Zur Provider-Konsole": "Back to provider console",
    "Öffentliche Demo - read-only": "Public demo - read only",
    "Änderungen werden nicht gespeichert. Nutze eine eigene DMARQ-Installation, um echte Einstellungen zu ändern.": "Changes are not saved. Use your own DMARQ installation to change real settings.",
}


CATALOGS: Dict[str, Dict[str, str]] = {"en": EN_TRANSLATIONS, "de": DE_TRANSLATIONS}


def normalize_locale(value: Optional[str], default: str = "en") -> str:
    """Normalize locale variants and fall back to a supported language."""
    candidate = (value or "").strip().lower().replace("_", "-")
    if candidate.startswith("de"):
        return "de"
    if candidate.startswith("en"):
        return "en"
    return "de" if (default or "").lower().startswith("de") else "en"


def resolve_request_locale(request: Request, default: str = "en") -> str:
    """Resolve explicit URL/cookie choices before the deployment default."""
    query_locale = request.query_params.get("lang") if "query_string" in request.scope else None
    explicit = query_locale or request.cookies.get(LOCALE_COOKIE)
    return normalize_locale(explicit, default=default)


def translate(message: str, locale: str) -> str:
    """Translate one source-language message with an English fallback."""
    return CATALOGS.get(normalize_locale(locale), {}).get(message, message)


def catalog_for_locale(locale: str) -> Dict[str, str]:
    """Return the immutable source catalog selected for a browser request."""
    return CATALOGS.get(normalize_locale(locale), {})


def template_locale_context(request: Request, default: str = "en") -> dict:
    """Build the locale variables injected into every Jinja template."""
    locale = resolve_request_locale(request, default=default)
    return {
        "locale": locale,
        "supported_locales": SUPPORTED_LOCALES,
        "_": lambda message: translate(message, locale),
    }
