"""Small, dependency-free localization layer for the server-rendered UI.

English remains the source language.  The browser receives the selected catalog
so Alpine-rendered and other client-side messages use the same translations as
the initial HTML response.
"""

from typing import Dict, Optional

from fastapi import Request

SUPPORTED_LOCALES = ("en", "de")
LOCALE_COOKIE = "dmarq_locale"


DE_TRANSLATIONS: Dict[str, str] = {
    # Application shell and shared actions
    "Dashboard": "Übersicht",
    "Domains": "Domänen",
    "Reports": "Berichte",
    "Mail Sources": "Mailquellen",
    "Members": "Mitglieder",
    "More": "Mehr",
    "More tools": "Weitere Werkzeuge",
    "Specialized tools": "Spezialwerkzeuge",
    "Settings": "Einstellungen",
    "Profile & Security": "Profil & Sicherheit",
    "Advanced tools": "Erweiterte Werkzeuge",
    "Forensic reports": "Forensische Berichte",
    "Forensic Reports": "Forensische Berichte",
    "TLS reports": "TLS-Berichte",
    "Setup assistant": "Einrichtungsassistent",
    "Release": "Version",
    "Sign out": "Abmelden",
    "Sign in": "Anmelden",
    "Workspace": "Arbeitsbereich",
    "Show release notes": "Versionshinweise anzeigen",
    "Current release": "Aktuelle Version",
    "What's changed": "Änderungen",
    "Full changelog": "Vollständiges Änderungsprotokoll",
    "Close": "Schließen",
    "Cancel": "Abbrechen",
    "Save": "Speichern",
    "Delete": "Löschen",
    "Edit": "Bearbeiten",
    "Add": "Hinzufügen",
    "Back": "Zurück",
    "Open": "Öffnen",
    "Reload": "Neu laden",
    "Refresh": "Aktualisieren",
    "Retry": "Erneut versuchen",
    "Loading…": "Wird geladen…",
    "Never": "Nie",
    "None": "Keine",
    "Status": "Status",
    "Details": "Details",
    "Description": "Beschreibung",
    "Advanced": "Erweitert",
    "General": "Allgemein",
    "Language": "Sprache",
    "English": "Englisch",
    "German": "Deutsch",
    "Choose the language used for navigation, guidance, dates, and numbers in this browser.": "Wähle die Sprache für Navigation, Hinweise, Datumsangaben und Zahlen in diesem Browser.",
    "Your explicit choice is kept in this browser and takes precedence over the instance default.": "Deine ausdrückliche Auswahl wird in diesem Browser gespeichert und hat Vorrang vor dem Instanzstandard.",
    "Account": "Konto",
    "Name": "Name",
    "Domain": "Domain",
    "Date": "Datum",
    "Owner": "Verantwortlich",
    "Priority": "Priorität",
    "View details": "Details anzeigen",
    "More actions": "Weitere Aktionen",
    "No action": "Keine Aktion",
    "Unknown": "Unbekannt",
    "Never": "Nie",
    "Complete": "Vollständig",
    "Setup needed": "Einrichtung erforderlich",
    "Connected": "Verbunden",
    "Not authorised": "Nicht autorisiert",
    "Ready to test": "Bereit zum Testen",
    "Needs configuration": "Konfiguration erforderlich",
    "Needs credentials": "Zugangsdaten erforderlich",
    "Planned": "Geplant",
    "Not configured": "Nicht konfiguriert",
    "mailbox": "Postfach",
    "folder": "Ordner",
    "authorized account": "autorisiertes Konto",
    "{count} error": "{count} Fehler",
    "{count} errors": "{count} Fehler",
    "No active alerts found.": "Keine aktiven Warnungen gefunden.",
    "{count} active alert found.": "{count} aktive Warnung gefunden.",
    "{count} active alerts found.": "{count} aktive Warnungen gefunden.",
    "{provider} discovery needs attention": "Die Erkennung bei {provider} benötigt Aufmerksamkeit",
    "{provider} returned no importable zones": "{provider} hat keine importierbaren Zonen zurückgegeben",
    "Loading": "Wird geladen",
    "Pass": "Bestanden",
    "Fail": "Fehlgeschlagen",
    "Clean": "Unauffällig",
    "Listed": "Gelistet",
    "Unchecked": "Nicht geprüft",
    "Recent": "Kürzlich",
    "All time": "Gesamter Zeitraum",
    "Last 7 days": "Letzte 7 Tage",
    "Last 14 days": "Letzte 14 Tage",
    "Last 30 days": "Letzte 30 Tage",
    "Last 90 days": "Letzte 90 Tage",
    "All Domains": "Alle Domains",
    "Date Range": "Zeitraum",
    # First-run dashboard
    "WELCOME TO DMARQ": "WILLKOMMEN BEI DMARQ",
    "Start by connecting your report mailbox": "Verbinde zuerst dein Berichts-Postfach",
    "DMARQ needs aggregate reports before it can identify senders, measure authentication, or recommend DNS changes.": "DMARQ benötigt aggregierte Berichte, bevor Absender erkannt, Authentifizierung gemessen oder DNS-Änderungen empfohlen werden können.",
    "Connect report mailbox": "Berichts-Postfach verbinden",
    "Other import options": "Weitere Importmöglichkeiten",
    "Report Intake Status": "Status des Berichtseingangs",
    "Trigger Poll Now": "Postfach jetzt prüfen",
    "No enabled sources": "Keine aktive Quelle",
    "Last Check:": "Letzte Prüfung:",
    "Sources:": "Quellen:",
    "Attention:": "Achtung:",
    "Open Mail Sources": "Mailquellen öffnen",
    "Loading configured mail sources...": "Konfigurierte Mailquellen werden geladen…",
    "No enabled mail sources configured": "Keine aktive Mailquelle konfiguriert",
    "Add or review domains": "Domains hinzufügen oder prüfen",
    "Already have a DMARC XML or ZIP file? Import it once instead of connecting a mailbox.": "Liegt bereits eine DMARC-XML- oder ZIP-Datei vor? Importiere sie einmalig, statt ein Postfach zu verbinden.",
    "Import report file": "Berichtsdatei importieren",
    "Loading dashboard data": "Übersichtsdaten werden geladen",
    "Dashboard could not be loaded": "Die Übersicht konnte nicht geladen werden",
    "Dashboard refresh failed": "Die Übersicht konnte nicht aktualisiert werden",
    "Open domains": "Domains öffnen",
    "Open reports": "Berichte öffnen",
    "Portfolio health": "Portfolio-Zustand",
    "Analytics and evidence": "Analysen und Nachweise",
    "Remediation Loop": "Behebungsprozess",
    "Current fix queue": "Aktuelle Aufgabenliste",
    "Open remediation queue": "Behebungsaufgaben öffnen",
    "No active remediation work queued": "Keine aktiven Behebungsaufgaben",
    "Next action:": "Nächste Aktion:",
    "Next safe action:": "Nächste sichere Aktion:",
    "Done when": "Erledigt, wenn",
    "Fresh evidence": "Aktuelle Nachweise",
    "Need fresh evidence": "Aktuelle Nachweise erforderlich",
    "Needs approval": "Freigabe erforderlich",
    "Resolved": "Erledigt",
    "Investigate": "Untersuchen",
    "Manual action": "Manuelle Aktion",
    "Emails": "E-Mails",
    "Enforcement Rate": "Durchsetzungsrate",
    "DNS Record Health": "DNS-Zustand",
    "DMARC Compliance Rate": "DMARC-Konformitätsrate",
    "Report intake blocked": "Berichtseingang blockiert",
    "Reconnect the report mailbox": "Berichts-Postfach erneut verbinden",
    "A connected mailbox needs authorization before scheduled imports can continue.": "Ein verbundenes Postfach benötigt eine erneute Autorisierung, bevor geplante Importe fortgesetzt werden können.",
    "Review mail source": "Mailquelle prüfen",
    "Report intake needs attention": "Berichtseingang benötigt Aufmerksamkeit",
    "Resolve the mailbox connection warning": "Warnung zur Postfachverbindung beheben",
    "DMARQ cannot rely on fresh evidence until the affected source succeeds again.": "DMARQ kann erst wieder auf aktuelle Nachweise vertrauen, wenn die betroffene Quelle erfolgreich geprüft wurde.",
    "{severity} priority": "Priorität: {severity}",
    "medium": "mittel",
    "Review the highest-priority domain issue": "Wichtigstes Domain-Problem prüfen",
    "Review current evidence before changing DNS or sender configuration.": "Prüfe die aktuellen Nachweise, bevor du DNS- oder Absender-Einstellungen änderst.",
    "Open remediation": "Behebung öffnen",
    "Monitoring": "Überwachung",
    "Review reports": "Berichte prüfen",
    "Report-backed domains only · {count} empty domain hidden": "Nur Domänen mit Berichten · {count} leere Domäne ausgeblendet",
    "Report-backed domains only · {count} empty domains hidden": "Nur Domänen mit Berichten · {count} leere Domänen ausgeblendet",
    "Import running": "Import läuft",
    "Scheduled checks active": "Geplante Prüfungen aktiv",
    "Needs attention": "Benötigt Aufmerksamkeit",
    "Stopped": "Angehalten",
    "Scheduled checks stopped": "Geplante Prüfungen angehalten",
    "No source configured": "Keine Quelle konfiguriert",
    # Settings runtime feedback
    "Failed to load settings": "Einstellungen konnten nicht geladen werden",
    "Error loading settings": "Fehler beim Laden der Einstellungen",
    "Failed to load account readiness": "Kontobereitschaft konnte nicht geladen werden",
    "Error loading account readiness": "Fehler beim Laden der Kontobereitschaft",
    "Failed to load DNS resolver status": "DNS-Resolver-Status konnte nicht geladen werden",
    "Error loading DNS resolver status": "Fehler beim Laden des DNS-Resolver-Status",
    "Save failed": "Speichern fehlgeschlagen",
    "Settings saved successfully.": "Einstellungen wurden gespeichert.",
    "Error saving settings": "Fehler beim Speichern der Einstellungen",
    "Automation settings saved.": "Automatisierungseinstellungen wurden gespeichert.",
    "Error saving automation settings": "Fehler beim Speichern der Automatisierungseinstellungen",
    "AI provider profiles failed": "KI-Anbieterprofile konnten nicht geladen werden",
    "Error loading AI provider profiles": "Fehler beim Laden der KI-Anbieterprofile",
    "AI connection failed": "KI-Verbindung fehlgeschlagen",
    "AI connection succeeded.": "KI-Verbindung erfolgreich hergestellt.",
    "Error testing AI connection": "Fehler beim Testen der KI-Verbindung",
    "Test failed": "Test fehlgeschlagen",
    "Test notification sent.": "Testbenachrichtigung wurde gesendet.",
    "Error sending test notification": "Fehler beim Senden der Testbenachrichtigung",
    "Alert check failed": "Warnungsprüfung fehlgeschlagen",
    "Error checking alerts": "Fehler beim Prüfen der Warnungen",
    "Alert send failed": "Senden der Warnung fehlgeschlagen",
    "No active alerts to send.": "Keine aktiven Warnungen zum Senden.",
    "Alert summary sent.": "Warnungsübersicht wurde gesendet.",
    "Error sending alerts": "Fehler beim Senden der Warnungen",
    "Summary preview failed": "Vorschau der Übersicht fehlgeschlagen",
    "Summary preview updated.": "Vorschau der Übersicht wurde aktualisiert.",
    "Error previewing summary": "Fehler beim Erstellen der Übersichtsvorschau",
    "Summary send failed": "Senden der Übersicht fehlgeschlagen",
    "Summary notification sent.": "Übersichtsbenachrichtigung wurde gesendet.",
    "Error sending summary": "Fehler beim Senden der Übersicht",
    # Domains
    "Domain Management": "Domainverwaltung",
    "Monitored Domains": "Überwachte Domänen",
    "Add monitored domain": "Überwachte Domain hinzufügen",
    "Edit monitored domain": "Überwachte Domain bearbeiten",
    "Loading monitored domains...": "Überwachte Domains werden geladen…",
    "No domains found. Add a domain to get started.": "Keine Domains gefunden. Füge eine Domain hinzu, um zu beginnen.",
    "All monitored domains are currently hidden because no reports or mail volume have been observed yet.": "Alle überwachten Domains sind ausgeblendet, weil noch keine Berichte oder E-Mail-Mengen vorliegen.",
    "Track DNS health and future DMARC reports before the first report arrives.": "Überwache DNS-Zustand und künftige DMARC-Berichte bereits vor dem ersten Bericht.",
    "DKIM selectors": "DKIM-Selektoren",
    "DMARC report mailbox override": "Abweichendes DMARC-Berichts-Postfach",
    "Sending Sources": "Versandquellen",
    "Domain detail": "Domain-Details",
    "Domain health grade": "Domain-Bewertung",
    "Current health score": "Aktueller Zustandswert",
    "Next remediation": "Nächste Behebung",
    "Action plan": "Aktionsplan",
    "Authentication review": "Authentifizierungsprüfung",
    "Current failures:": "Aktuelle Fehler:",
    "Current passes:": "Aktuell bestanden:",
    "Failed emails": "Fehlgeschlagene E-Mails",
    "First seen": "Erstmals gesehen",
    "Last seen": "Zuletzt gesehen",
    "Last sent": "Zuletzt gesendet",
    "Captured during processing": "Bei der Verarbeitung erfasst",
    "Source intelligence": "Absenderinformationen",
    "Country unknown": "Land unbekannt",
    "Geo unavailable": "Geodaten nicht verfügbar",
    "PTR unavailable": "PTR nicht verfügbar",
    "Pending DNS refresh": "DNS-Aktualisierung ausstehend",
    "DNS queued": "DNS-Prüfung eingeplant",
    "DNS failed": "DNS-Prüfung fehlgeschlagen",
    "Last known DNS": "Letzter bekannter DNS-Stand",
    "Fallback DNS": "DNS-Ausweichdaten",
    "Partial DNS": "Unvollständige DNS-Daten",
    "Cached DNS": "Zwischengespeicherte DNS-Daten",
    "Fresh DNS": "Aktuelle DNS-Daten",
    "Checked {value}": "Geprüft: {value}",
    "Unknown sender": "Unbekannter Absender",
    "Observed messages": "Beobachtete Nachrichten",
    "DMARC failure rate": "DMARC-Fehlerrate",
    "Reputation review": "Reputationsprüfung",
    "Clean reputation": "Unauffällige Reputation",
    "Recalculate reputation": "Reputation neu berechnen",
    "Show IP evidence": "IP-Nachweise anzeigen",
    "Open in Cloudflare Radar": "In Cloudflare Radar öffnen",
    "Recommended next steps": "Empfohlene nächste Schritte",
    "Raw record evidence": "Unverarbeitete Nachweise",
    # Reports
    "DMARC Reports": "DMARC-Berichte",
    "Aggregate evidence": "Aggregierte Nachweise",
    "Review imported aggregate reports, then open the first failing report or connect a report source.": "Prüfe importierte aggregierte Berichte. Öffne anschließend den ersten fehlerhaften Bericht oder verbinde eine Berichtsquelle.",
    "Reset Filters": "Filter zurücksetzen",
    "Type": "Typ",
    "Pass Rate": "Erfolgsquote",
    "Actions": "Aktionen",
    "Showing {count} reports": "{count} Berichte angezeigt",
    "Aggregate": "Aggregiert",
    "Check Mail Sources": "Mailquellen prüfen",
    "Open first failing report": "Ersten fehlerhaften Bericht öffnen",
    "Open latest report": "Neuesten Bericht öffnen",
    "No reports match this filter": "Keine Berichte entsprechen diesem Filter",
    "No DMARC reports imported yet": "Noch keine DMARC-Berichte importiert",
    "Change the filters or reset them to get back to imported reports.": "Ändere die Filter oder setze sie zurück, um wieder importierte Berichte anzuzeigen.",
    "Connect Gmail, IMAP, or another report source so DMARQ can import aggregate XML reports.": "Verbinde Gmail, IMAP oder eine andere Berichtsquelle, damit DMARQ aggregierte XML-Berichte importieren kann.",
    "Reporter": "Berichtanbieter",
    "Messages": "Nachrichten",
    "Loading reports...": "Berichte werden geladen…",
    "Checking report index...": "Berichtsindex wird geprüft…",
    "Reports unavailable": "Berichte nicht verfügbar",
    "Retry loading reports": "Berichte erneut laden",
    "Trigger report refresh": "Berichte aktualisieren",
    "This should only take a moment. If it stays empty, open Mail Sources and check the last import.": "Dies sollte nur einen Moment dauern. Bleibt die Ansicht leer, öffne die Mailquellen und prüfe den letzten Import.",
    "Aggregate report": "Aggregierter Bericht",
    "Report ID": "Berichts-ID",
    "Organization": "Organisation",
    "Period Start": "Zeitraum von",
    "Period End": "Zeitraum bis",
    "Messages covered": "Erfasste Nachrichten",
    "Authentication rate": "Authentifizierungsrate",
    "DMARC aligned": "DMARC-konform",
    "All records": "Alle Einträge",
    "No records in this report": "Dieser Bericht enthält keine Einträge",
    "No records match this reputation view.": "Keine Einträge entsprechen dieser Reputationsansicht.",
    "Expand individual IP, authentication, reputation, and policy results.": "Blende einzelne IP-, Authentifizierungs-, Reputations- und Richtlinienergebnisse ein.",
    # Mail sources
    "Add Mail Source": "Mailquelle hinzufügen",
    "Edit settings": "Einstellungen bearbeiten",
    "Test Connection": "Verbindung testen",
    "Enable this mail source": "Diese Mailquelle aktivieren",
    "Polling Interval (minutes)": "Prüfintervall (Minuten)",
    "Historical import": "Historischer Import",
    "Backfill Mail Source": "Mailquelle rückwirkend importieren",
    "Backfill date range": "Zeitraum des rückwirkenden Imports",
    "Days to search": "Zu durchsuchende Tage",
    "Run first backfill": "Ersten rückwirkenden Import starten",
    "Import history": "Importverlauf",
    "No import attempts recorded yet.": "Noch keine Importversuche erfasst.",
    "No backfill has been run for this account.": "Für dieses Konto wurde noch kein rückwirkender Import ausgeführt.",
    "Last mailbox check": "Letzte Postfachprüfung",
    "Connect Gmail": "Gmail verbinden",
    "Connect Microsoft 365": "Microsoft 365 verbinden",
    "Authentication": "Authentifizierung",
    "Password": "Passwort",
    "Leave blank to keep the saved password": "Leer lassen, um das gespeicherte Passwort beizubehalten",
    "Save the source first, then edit it to test mailbox access and load folders.": "Speichere die Quelle zuerst. Bearbeite sie anschließend, um den Postfachzugriff zu testen und Ordner zu laden.",
    "Delete Mail Source": "Mailquelle löschen",
    "Delete account": "Konto löschen",
    "Test application access": "Anwendungszugriff testen",
    "Application access": "Anwendungszugriff",
    "Mail.Read application permission": "Anwendungsberechtigung Mail.Read",
    "Limit mailbox access in Exchange Online": "Postfachzugriff in Exchange Online einschränken",
    "Duplicates": "Duplikate",
    "Errors": "Fehler",
    "Recognized": "Erkannt",
    "Ignored": "Ignoriert",
    "Queued": "Eingeplant",
    "Running": "Läuft",
    "Backoff": "Wartet auf erneuten Versuch",
    "Cancelled": "Abgebrochen",
    "Completed": "Abgeschlossen",
    "Retry {value}": "Erneuter Versuch: {value}",
    "{count} day": "{count} Tag",
    "{count} days": "{count} Tage",
    "Default search window": "Standard-Suchzeitraum",
    "Manage inbox accounts used to automatically retrieve DMARC reports.": "Verwalte Postfachkonten, über die DMARC-Berichte automatisch abgerufen werden.",
    "Multiple accounts and connection methods (IMAP, POP3, Gmail API, Microsoft 365) are supported.": "Mehrere Konten und Verbindungsmethoden (IMAP, POP3, Gmail API, Microsoft 365) werden unterstützt.",
    "No mail sources configured yet. Click Add Mail Source to get started.": "Noch keine Mailquellen konfiguriert. Klicke auf Mailquelle hinzufügen, um zu beginnen.",
    "Polling on": "Postfachabfrage aktiv",
    "Polling off": "Postfachabfrage aus",
    "Import now": "Jetzt importieren",
    "Importing…": "Import läuft…",
    "Latest backfill": "Letzter rückwirkender Import",
    "Loading latest backfill…": "Letzter rückwirkender Import wird geladen…",
    "Checked": "Geprüft",
    "New": "Neu",
    "Existing": "Bereits vorhanden",
    "Review import warning": "Importwarnung prüfen",
    "Queued to scan {window}.": "{window} wurde zur Prüfung eingeplant.",
    "Scanning {window}; {processed} messages checked and {recognized} reports recognized.": "{window} wird geprüft; {processed} Nachrichten geprüft und {recognized} Berichte erkannt.",
    "Retry scheduled after {errors} error(s); attempt {attempt} of {maxAttempts}.": "Neuer Versuch nach {errors} Fehler(n) eingeplant; Versuch {attempt} von {maxAttempts}.",
    "Completed {window}; {recognized} reports recognized ({fresh} new, {existing} already imported).": "{window} abgeschlossen; {recognized} Berichte erkannt ({fresh} neu, {existing} bereits importiert).",
    "{count} unrelated attachment(s) ignored.": "{count} nicht zugehörige Anlage(n) ignoriert.",
    "Failed after attempt {attempt} of {maxAttempts}.": "Nach Versuch {attempt} von {maxAttempts} fehlgeschlagen.",
    "Cancelled after checking {processed} messages.": "Nach Prüfung von {processed} Nachrichten abgebrochen.",
    "Backfill status is available.": "Status des rückwirkenden Imports ist verfügbar.",
    # Settings
    "Recommended setup": "Empfohlene Einrichtung",
    "Finish the next safe setup step": "Führe den nächsten sicheren Einrichtungsschritt aus",
    "Connect the mailbox that receives DMARC reports first. Add domains and DNS automation only after report intake is working.": "Verbinde zuerst das Postfach, das DMARC-Berichte empfängt. Füge Domains und DNS-Automatisierung erst hinzu, wenn der Berichtseingang funktioniert.",
    "Connect reports": "Berichte verbinden",
    "Add domains": "Domains hinzufügen",
    "Review DNS": "DNS prüfen",
    "Choose notifications": "Benachrichtigungen auswählen",
    "Setup": "Einrichtung",
    "DMARC defaults": "DMARC-Standards",
    "Domains and DNS": "Domains und DNS",
    "Notifications": "Benachrichtigungen",
    "Report mailbox": "Berichts-Postfach",
    "DNS resolver": "DNS-Auflösung",
    "Sender imports": "Absenderimporte",
    "Privacy": "Datenschutz",
    "Webhooks": "Webhooks",
    "AI and agents": "KI und Agenten",
    "Account diagnostics": "Kontodiagnose",
    "Application Name": "Anwendungsname",
    "Base URL": "Basis-URL",
    "Reports per page": "Berichte pro Seite",
    "Reports Per Page": "Berichte pro Seite",
    "Session lifetime (minutes)": "Sitzungsdauer (Minuten)",
    "Session Lifetime (minutes)": "Sitzungsdauer (Minuten)",
    "How many reports are shown per page": "Wie viele Berichte pro Seite angezeigt werden",
    "How long login sessions remain valid": "Wie lange Anmeldesitzungen gültig bleiben",
    "Save General Settings": "Allgemeine Einstellungen speichern",
    "DNS Resolver": "DNS-Auflösung",
    "Resolver ready": "DNS-Auflösung bereit",
    "Using safe DNS fallback": "Sichere DNS-Ausweichlösung wird verwendet",
    "DNS Provider Connectors": "DNS-Anbieter verbinden",
    "Account and access diagnostics": "Konto- und Zugriffsdiagnose",
    "Loading account readiness...": "Kontobereitschaft wird geladen…",
    "Aggregate report mailbox": "Postfach für aggregierte Berichte",
    "Daily summary": "Tägliche Zusammenfassung",
    "Weekly summary": "Wöchentliche Zusammenfassung",
    "Enable notifications": "Benachrichtigungen aktivieren",
    "Save Settings": "Einstellungen speichern",
    "Settings saved successfully": "Einstellungen wurden gespeichert",
    "Failed to save settings": "Einstellungen konnten nicht gespeichert werden",
    "Authentication, roles, billing, and support readiness": "Authentifizierung, Rollen, Abrechnung und Support-Bereitschaft",
    "Safety boundary": "Sicherheitsgrenze",
    "Refreshing...": "Wird aktualisiert…",
    "Production mail domain": "Produktive Mail-Domain",
    "Use global default mailbox": "Globales Standard-Postfach verwenden",
    "visible monitored domain": "sichtbare überwachte Domäne",
    "visible monitored domains": "sichtbare überwachte Domänen",
    "without reports or volume hidden": "ohne Berichte oder Volumen ausgeblendet",
    "Show empty domains": "Leere Domänen anzeigen",
    "Refresh queue": "Aufgabenliste aktualisieren",
    "Refresh DNS": "DNS aktualisieren",
    "Refresh DNS evidence": "DNS-Nachweise aktualisieren",
    "Refreshing DNS...": "DNS wird aktualisiert…",
    "Reload data": "Daten neu laden",
    "Read-only demo: changes are disabled.": "Nur-Lese-Demo: Änderungen sind deaktiviert.",
    # First-run setup
    "First-run setup": "Ersteinrichtung",
    "Save the basic settings DMARQ needs before the dashboard is used.": "Speichere die Grundeinstellungen, die DMARQ vor der ersten Nutzung benötigt.",
    "Open dashboard": "Übersicht öffnen",
    "Setup progress": "Einrichtungsfortschritt",
    "Operational contact": "Betrieblicher Kontakt",
    "System": "System",
    "Name and URL": "Name und URL",
    "Ready": "Bereit",
    "Start using DMARQ": "DMARQ verwenden",
    "Checking setup status...": "Einrichtungsstatus wird geprüft…",
    "Owner contact": "Kontaktperson",
    "This is an operational contact, not a login account. Sign-in is controlled by the authentication mode shown on this page.": "Dies ist ein betrieblicher Kontakt, kein Anmeldekonto. Die Anmeldung richtet sich nach dem auf dieser Seite gezeigten Authentifizierungsmodus.",
    "Owner email": "E-Mail der Kontaktperson",
    "Used only as the deployment contact in setup records.": "Wird nur als Bereitstellungskontakt in den Einrichtungsdaten verwendet.",
    "Continue": "Weiter",
    "System settings": "Systemeinstellungen",
    "These values are stored in the application settings.": "Diese Werte werden in den Anwendungseinstellungen gespeichert.",
    "Application name": "Anwendungsname",
    "Connect Cloudflare during setup": "Cloudflare während der Einrichtung verbinden",
    "Use a scoped Cloudflare API token to verify zone ownership, import domains, and prepare DNS repair previews. The token is sent directly to DMARQ and encrypted at rest.": "Nutze einen eingeschränkten Cloudflare-API-Token, um Zoneninhaberschaft zu prüfen, Domänen zu importieren und DNS-Behebungsvorschauen vorzubereiten. Der Token wird direkt an DMARQ übertragen und verschlüsselt gespeichert.",
    "Cloudflare API token": "Cloudflare-API-Token",
    "Zone read permission is enough for discovery; DNS edit is only needed for approved repairs.": "Leserechte für Zonen reichen zur Erkennung aus; DNS-Schreibrechte werden nur für freigegebene Behebungen benötigt.",
    "Default Zone ID": "Standard-Zonen-ID",
    "Optional. Leave empty when this token can access multiple zones.": "Optional. Leer lassen, wenn dieser Token auf mehrere Zonen zugreifen kann.",
    "Finish setup": "Einrichtung abschließen",
    "Setup is complete.": "Einrichtung abgeschlossen.",
    "DMARQ is ready for report ingestion.": "DMARQ ist bereit, Berichte zu importieren.",
    "Connect mailbox": "Postfach verbinden",
    "Choose the authentication mode that matches this deployment.": "Wähle den Authentifizierungsmodus, der zu dieser Bereitstellung passt.",
    "Setup checklist": "Einrichtungscheckliste",
    "Add monitored domains": "Überwachte Domänen hinzufügen",
    "Connect a mailbox": "Postfach verbinden",
    "Check system health": "Systemzustand prüfen",
    "Could not load setup status.": "Einrichtungsstatus konnte nicht geladen werden.",
    "Enter a Cloudflare API token or leave Cloudflare disabled for now.": "Gib einen Cloudflare-API-Token ein oder lasse Cloudflare vorerst deaktiviert.",
    "Your setup settings and Cloudflare connector have been saved.": "Deine Einrichtungseinstellungen und die Cloudflare-Verbindung wurden gespeichert.",
    "Your setup settings have been saved.": "Deine Einrichtungseinstellungen wurden gespeichert.",
    "Setup could not be saved.": "Einrichtung konnte nicht gespeichert werden.",
    "({count} configured)": "({count} konfiguriert)",
    "({enabled}/{total} enabled)": "({enabled}/{total} aktiv)",
    "No enabled mailbox source is available for scheduled DMARC imports.": "Für geplante DMARC-Importe ist keine aktive Postfachquelle verfügbar.",
    "Add or enable a mail source that receives DMARC aggregate reports.": "Füge eine Mailquelle hinzu oder aktiviere sie, die aggregierte DMARC-Berichte empfängt.",
    "Run Test Connection before relying on scheduled imports.": "Führe Verbindung testen aus, bevor du dich auf geplante Importe verlässt.",
    "No app auth": "Keine Anmeldepflicht in der App",
    "disabled": "deaktiviert",
    "Self-hosted behind a trusted network, VPN, or access proxy": "Selbst gehostet hinter einem vertrauenswürdigen Netzwerk, VPN oder Zugriffsproxy",
    "Use only when DMARQ is protected outside the app. Public unauthenticated deployments are blocked in production unless explicitly allowed.": "Nur verwenden, wenn DMARQ außerhalb der Anwendung geschützt ist. Öffentliche, nicht authentifizierte Bereitstellungen sind in Produktion gesperrt, sofern sie nicht ausdrücklich erlaubt wurden.",
    "Hosted or self-hosted OIDC identity provider": "Gehosteter oder selbst gehosteter OIDC-Identitätsanbieter",
    "Set LOGTO_ENDPOINT, LOGTO_APP_ID, and LOGTO_APP_SECRET.": "Setze LOGTO_ENDPOINT, LOGTO_APP_ID und LOGTO_APP_SECRET.",
    "Direct Authentik OAuth2/OpenID provider": "Direkter Authentik-OAuth2-/OpenID-Anbieter",
    "Create an Authentik OAuth2/OpenID provider and set AUTHENTIK_ISSUER_URL, AUTHENTIK_CLIENT_ID, and AUTHENTIK_CLIENT_SECRET.": "Erstelle einen Authentik-OAuth2-/OpenID-Anbieter und setze AUTHENTIK_ISSUER_URL, AUTHENTIK_CLIENT_ID und AUTHENTIK_CLIENT_SECRET.",
    "Reverse-proxy enforced SSO in front of DMARQ": "Durch Reverse Proxy erzwungenes SSO vor DMARQ",
    "Use only when the proxy is the sole public path to DMARQ and strips any incoming spoofed identity headers.": "Nur verwenden, wenn der Proxy der einzige öffentliche Zugang zu DMARQ ist und eingehende gefälschte Identitäts-Header entfernt.",
    "Provider-neutral OIDC for Keycloak, Entra ID, Google, Okta, and others": "Anbieterneutrales OIDC für Keycloak, Entra ID, Google, Okta und weitere",
    "Set OIDC_ISSUER_URL, OIDC_CLIENT_ID, OIDC_CLIENT_SECRET, and optionally OIDC_PROVIDER_LABEL plus allowlists.": "Setze OIDC_ISSUER_URL, OIDC_CLIENT_ID, OIDC_CLIENT_SECRET sowie optional OIDC_PROVIDER_LABEL und Allow-Listen.",
    "Self-hosted or enterprise Keycloak realm/client": "Selbst gehosteter oder Enterprise-Keycloak-Realm/-Client",
    "Use AUTH_MODE=oidc and set OIDC_PROVIDER_LABEL=Keycloak.": "Verwende AUTH_MODE=oidc und setze OIDC_PROVIDER_LABEL=Keycloak.",
    "Commercial enterprise IdP": "Kommerzieller Enterprise-Identitätsanbieter",
    "Use AUTH_MODE=oidc with the Entra issuer and group/app-role claims.": "Verwende AUTH_MODE=oidc mit dem Entra-Issuer und Gruppen- bzw. App-Rollen-Claims.",
    "Google-managed identity for self-hosted or team deployments": "Von Google verwaltete Identität für selbst gehostete oder Team-Bereitstellungen",
    "Use AUTH_MODE=oidc and restrict access with OIDC_ALLOWED_EMAILS or domains.": "Verwende AUTH_MODE=oidc und beschränke den Zugriff mit OIDC_ALLOWED_EMAILS oder Domains.",
    # Empty/error/success states
    "No data available": "Keine Daten verfügbar",
    "No results found": "Keine Ergebnisse gefunden",
    "Something went wrong": "Etwas ist schiefgelaufen",
    "Try again": "Erneut versuchen",
    "Connection successful": "Verbindung erfolgreich",
    "Connection failed": "Verbindung fehlgeschlagen",
    "Saving…": "Wird gespeichert…",
    "Saved": "Gespeichert",
    # Dashboard and remediation details
    "DMARQ is checking domains, report volume, DNS health, and sender signals.": "DMARQ prüft Domains, Berichtsvolumen, DNS-Zustand und Absendersignale.",
    "No immediate remediation action": "Keine sofortige Behebung erforderlich",
    "Keep report intake running and review new sender or DNS changes when they appear.": "Lasse den Berichtseingang weiterlaufen und prüfe neue Absender- oder DNS-Änderungen, sobald sie auftreten.",
    "Report-backed domains only": "Nur Domains mit Berichten",
    "View domains": "Domains anzeigen",
    "No report-backed domain selected": "Keine Domain mit Berichten ausgewählt",
    "Policy: unknown": "Richtlinie: unbekannt",
    "No sending source data available": "Keine Daten zu Versandquellen verfügbar",
    "No failures": "Keine Fehler",
    "Recent source and compliance changes": "Aktuelle Änderungen bei Absendern und Konformität",
    "Review evidence": "Nachweise prüfen",
    "No major sender or compliance changes detected.": "Keine wesentlichen Änderungen bei Absendern oder Konformität erkannt.",
    "Domain Compliance": "Domain-Konformität",
    "All-time imported evidence. Open a domain for the complete remediation plan.": "Importierte Nachweise über den gesamten Zeitraum. Öffne eine Domain für den vollständigen Behebungsplan.",
    "Domain health breakdown": "Verteilung des Domain-Zustands",
    "Traffic-weighted health": "Nach Volumen gewichteter Zustand",
    "No prior score": "Kein vorheriger Wert",
    "Additional fixes after the primary next action above.": "Weitere Behebungen nach der oben genannten nächsten Hauptaktion.",
    "No additional remediation actions. Keep monitoring reports and DNS drift.": "Keine weiteren Behebungsaktionen. Überwache weiterhin Berichte und DNS-Abweichungen.",
    "Domain Grades": "Domain-Bewertungen",
    "Last 24 hours": "Letzte 24 Stunden",
    "Last 48 hours": "Letzte 48 Stunden",
    "Week to date": "Laufende Woche",
    "Month to date": "Laufender Monat",
    "Advanced remediation workflow": "Erweiterter Behebungsprozess",
    "Keep importing reports and monitoring DNS.": "Importiere weiterhin Berichte und überwache DNS.",
    "Open domain worklist": "Domain-Aufgaben öffnen",
    "Queue controls and operational metrics": "Aufgabensteuerung und Betriebskennzahlen",
    "Keep the remediation loop open until every closure gate is represented.": "Lasse den Behebungsprozess offen, bis alle Abschlusskriterien erfüllt sind.",
    "Resolved items no longer observed": "Erledigte Punkte werden nicht mehr beobachtet",
    "DNS or policy changes to review": "Zu prüfende DNS- oder Richtlinienänderungen",
    "waiting for explicit approval": "wartet auf ausdrückliche Freigabe",
    "Tasks for mail or DNS owners": "Aufgaben für Mail- oder DNS-Verantwortliche",
    "Sender or report evidence to confirm": "Zu bestätigende Absender- oder Berichtsnachweise",
    "Repair previews ready": "Behebungsvorschauen bereit",
    "Provider-backed proposals ready for review": "Anbietergestützte Vorschläge zur Prüfung bereit",
    "Notifications ready": "Benachrichtigungen bereit",
    "Missing provider values or prerequisites": "Fehlende Anbieterwerte oder Voraussetzungen",
    "Preview ready": "Vorschau bereit",
    "Ready to notify": "Benachrichtigung bereit",
    "Report evidence": "Berichtsnachweis",
    "Stale evidence": "Veralteter Nachweis",
    "Choose another queue view or refresh after new evidence is available.": "Wähle eine andere Aufgabenansicht oder aktualisiere, sobald neue Nachweise vorliegen.",
    "Show all remediation cards": "Alle Behebungsaufgaben anzeigen",
    "Welcome to DMARQ": "Willkommen bei DMARQ",
    "Upload a report file": "Berichtsdatei hochladen",
    "Change the evidence window": "Nachweiszeitraum ändern",
    "Next": "Weiter",
    # Domain workbench
    "Add Domain": "Domain hinzufügen",
    "DMARC Status": "DMARC-Status",
    "SPF Status": "SPF-Status",
    "DKIM Status": "DKIM-Status",
    "Optional. Leave empty to use the aggregate report mailbox from Settings or dmarc@domain.": "Optional. Leer lassen, um das Postfach für aggregierte Berichte aus den Einstellungen oder dmarc@domain zu verwenden.",
    "Add domain": "Domain hinzufügen",
    "Save changes": "Änderungen speichern",
    "Check DNS records": "DNS-Einträge prüfen",
    "Delete domain": "Domain löschen",
    "Loading next remediation...": "Nächste Behebung wird geladen…",
    "Domain ownership and DNS write safety": "Domaininhaberschaft und sichere DNS-Änderungen",
    "Domain Ownership": "Domaininhaberschaft",
    "Proof status for DNS writes and one-click repair; report ingestion does not require this gate.": "Nachweisstatus für DNS-Änderungen und Ein-Klick-Behebung; der Berichtsimport benötigt dieses Kriterium nicht.",
    "Check ownership": "Inhaberschaft prüfen",
    "Daily DMARC volume, pass rate, and failure rate": "Tägliches DMARC-Volumen sowie Erfolgs- und Fehlerrate",
    "Advanced remediation and posture": "Erweiterte Behebung und Sicherheitslage",
    "Evidence-linked coverage, drift, and operator playbooks": "Nachweisbasierte Abdeckung, Abweichungen und Betriebsabläufe",
    "Prioritized fixes with evidence, prerequisites, and approval status.": "Priorisierte Behebungen mit Nachweisen, Voraussetzungen und Freigabestatus.",
    "approval-ready": "freigabebereit",
    "preview ready": "Vorschau bereit",
    "need evidence": "Nachweis erforderlich",
    "ready to notify": "Benachrichtigung bereit",
    "Loading remediation queue...": "Behebungsaufgaben werden geladen…",
    "Filter and sort queue": "Aufgaben filtern und sortieren",
    "Needs evidence": "Nachweis erforderlich",
    "Health history": "Zustandsverlauf",
    "Health Score Trend": "Verlauf des Zustandswerts",
    "Score movement, top drivers, and audit-ready evidence for this domain": "Wertentwicklung, wichtigste Einflussfaktoren und revisionsfähige Nachweise für diese Domain",
    "Export evidence": "Nachweise exportieren",
    "No previous score": "Kein vorheriger Wert",
    "No snapshot": "Keine Momentaufnahme",
    "No active score drivers in the latest snapshot.": "Keine aktiven Einflussfaktoren in der neuesten Momentaufnahme.",
    "Evidence window": "Nachweiszeitraum",
    "Export includes aggregate score evidence only; forensic message bodies are not included.": "Der Export enthält nur aggregierte Bewertungsnachweise; forensische Nachrichteninhalte sind nicht enthalten.",
    "Source platform": "Quellplattform",
    "Source": "Quelle",
    "DNS and authentication": "DNS und Authentifizierung",
    "DNS Records": "DNS-Einträge",
    "Email authentication DNS records for this domain": "DNS-Einträge zur E-Mail-Authentifizierung dieser Domain",
    "Looking up authoritative nameservers and authentication records.": "Autoritative Nameserver und Authentifizierungseinträge werden abgefragt.",
    "Checking provider connection and safe DNS repair options.": "Anbieterverbindung und sichere DNS-Behebungsmöglichkeiten werden geprüft.",
    "No live writes": "Keine direkten Änderungen",
    "Wait for DNS checks to complete.": "Warte, bis die DNS-Prüfungen abgeschlossen sind.",
    "No _mta-sts TXT record found": "Kein _mta-sts-TXT-Eintrag gefunden",
    "No BIMI TXT record found at default._bimi": "Kein BIMI-TXT-Eintrag unter default._bimi gefunden",
    "No manually configured selectors yet.": "Noch keine manuell konfigurierten Selektoren.",
    "Selector evidence": "Selektornachweise",
    "No DNS lint findings.": "Keine DNS-Prüffunde.",
    "Work through DMARC, SPF, and DKIM in this order before tightening enforcement.": "Bearbeite DMARC, SPF und DKIM in dieser Reihenfolge, bevor die Durchsetzung verschärft wird.",
    "Optional transport and branding records": "Optionale Transport- und Markeneinträge",
    "Source Intelligence": "Absenderinformationen",
    "Regions, networks, and unusual sending-source changes for this domain": "Regionen, Netzwerke und ungewöhnliche Änderungen der Versandquellen dieser Domain",
    "New sending source": "Neue Versandquelle",
    "Confirm ownership before authorizing this source in DNS.": "Bestätige die Verantwortlichkeit, bevor diese Quelle im DNS autorisiert wird.",
    "IP addresses and servers sending email as this domain": "IP-Adressen und Server, die E-Mails für diese Domain senden",
    "Loading sending sources...": "Versandquellen werden geladen…",
    "Latest DMARC reports received for this domain": "Neueste DMARC-Berichte für diese Domain",
    "View": "Anzeigen",
    # Settings and mailbox details
    "Configured Accounts": "Konfigurierte Konten",
    "Import new reports, review mailbox health, or run a historical backfill.": "Importiere neue Berichte, prüfe den Postfachzustand oder starte einen historischen Import.",
    "No mail sources configured yet. Click": "Noch keine Mailquellen konfiguriert. Klicke",
    "How often to check for new reports (min 15 min)": "Intervall für neue Berichte (mindestens 15 Minuten)",
    "Queues a resumable mailbox search. Progress appears in the Backfill column.": "Startet eine fortsetzbare Postfachsuche. Der Fortschritt erscheint in der Spalte für historische Importe.",
    "Basic application settings": "Grundlegende Anwendungseinstellungen",
    "Display name shown in the navigation bar and page titles": "Anzeigename in Navigation und Seitentiteln",
    "Public URL used in OAuth2 redirect URIs and email links": "Öffentliche URL für OAuth2-Weiterleitungen und E-Mail-Links",
    "DMARC Policy Defaults": "DMARC-Richtlinienstandards",
    "Default values applied when adding a new domain": "Standardwerte für neu hinzugefügte Domains",
    "Default Policy": "Standardrichtlinie",
    "Quarantine (send to spam)": "Quarantäne (als Spam behandeln)",
    "TLS report mailbox": "Postfach für TLS-Berichte",
    "Choose how DMARQ resolves DNS records for domain lookups": "Lege fest, wie DMARQ DNS-Einträge für Domainabfragen auflöst",
    "Provider Domain Discovery": "Domains beim Anbieter erkennen",
    "Find DNS zones and import them into DMARQ before reports arrive.": "Finde DNS-Zonen und importiere sie in DMARQ, bevor Berichte eintreffen.",
    "Provider setup docs": "Dokumentation zur Anbietereinrichtung",
    "Advanced privacy settings": "Erweiterte Datenschutzeinstellungen",
    "Control privacy for forensic report metadata": "Datenschutz für Metadaten forensischer Berichte steuern",
    "No alert history yet.": "Noch kein Alarmverlauf.",
    "No configuration changes recorded yet.": "Noch keine Konfigurationsänderungen erfasst.",
    "Check Alerts": "Alarme prüfen",
    "Advanced webhook delivery": "Erweiterte Webhook-Zustellung",
    "Signed event fan-out and delivery history": "Signierte Ereignisverteilung und Zustellverlauf",
    "No outbound webhooks configured yet.": "Noch keine ausgehenden Webhooks konfiguriert.",
    "No webhook deliveries recorded yet.": "Noch keine Webhook-Zustellungen erfasst.",
    "Advanced AI and agent automation": "Erweiterte KI- und Agentenautomatisierung",
    "Opt-in model and MCP controls": "Optionale Modell- und MCP-Steuerung",
    "AI and Agent Automation": "KI- und Agentenautomatisierung",
    "Use deterministic local remediation templates. No token or network call.": "Verwende deterministische lokale Behebungsvorlagen. Kein Token und kein Netzwerkaufruf.",
}


# The provider demo predates the common English source-language convention.
# Keep its existing copy stable while making the English product mode complete.
EN_TRANSLATIONS: Dict[str, str] = {
    "Abbrechen": "Cancel",
    "Abrechnung und Plan gelten für dieses Kundenkonto.": "Billing and plan apply to this customer account.",
    "Abrechnungsmodell": "Billing model",
    "Account erstellen": "Create account",
    "Account öffnen": "Open account",
    "Account-, Import-, Billing- und Support-Ereignisse.": "Account, import, billing, and support events.",
    "Account-Kontakt": "Account contact",
    "Aktivitätsprotokoll": "Activity log",
    "Aktuell": "Current",
    "Alle anzeigen": "Show all",
    "Als Kunde öffnen": "Open as customer",
    "Ansicht als": "Viewing as",
    "Authentifizierung, Policy und Berichtseingang im Account.": "Authentication, policy, and report intake for this account.",
    "Benutzer": "Users",
    "Benutzer einladen": "Invite user",
    "Billing bearbeiten": "Edit billing",
    "Billing speichern": "Save billing",
    "Domains / Benutzer": "Domains / users",
    "Erneut versuchen": "Try again",
    "Filter zurücksetzen oder ein neues Kundenkonto anlegen.": "Reset the filters or create a new customer account.",
    "Firmenname": "Company name",
    "Grund": "Reason",
    "Handlungsbedarf": "Needs attention",
    "Handlungsbedarf zuerst": "Needs attention first",
    "Interaktive Demo:": "Interactive demo:",
    "Keine passenden Accounts": "No matching accounts",
    "Kontakt": "Contact",
    "Kundenansicht öffnen": "Open customer view",
    "Kundenkonten": "Customer accounts",
    "Kundenkonten verwalten": "Manage customer accounts",
    "Kundenkonto anlegen": "Create customer account",
    "Letzter Report": "Latest report",
    "Mails · 30 T.": "Messages · 30 d.",
    "Mails · 30 Tage": "Messages · 30 days",
    "Mailvolumen": "Mail volume",
    "Mailvolumen · 30 Tage": "Mail volume · 30 days",
    "Monatlich": "Monthly",
    "Monatlicher Betrag": "Monthly amount",
    "Monatlicher Umsatz": "Monthly revenue",
    "Nach Risiko sortiert. Der nächste sinnvolle Schritt bleibt pro Account sichtbar.": "Sorted by risk. The next useful action stays visible for every account.",
    "Neues Kundenkonto": "New customer account",
    "Nächste sinnvolle Aktion": "Next useful action",
    "Offene Hinweise": "Open findings",
    "Organisationsinhaber": "Organization owner",
    "Primäre Domain": "Primary domain",
    "Protokollierter Support-Zugriff": "Audited support access",
    "Provider-Daten werden geladen...": "Loading provider data...",
    "Provider-Rechnung": "Provider invoice",
    "Provider-Verwaltung": "Provider management",
    "Provider-Verwaltung konnte nicht geladen werden": "Provider management could not be loaded",
    "Rechnungsempfänger": "Invoice recipient",
    "Rechnungsreferenz": "Invoice reference",
    "Schließen": "Close",
    "Sicherheitsrahmen": "Security controls",
    "Single-user-Demo": "Single-user demo",
    "Sortierung": "Sort order",
    "Suche": "Search",
    "Support-Ansicht": "Support view",
    "Support-Sitzung starten": "Start support session",
    "Testphase": "Trial",
    "Umsatz": "Revenue",
    "Vertragsrechnung": "Contract invoice",
    "Zuletzt aktiv": "Last active",
    "kritisch, auffällig oder überfällig": "critical, notable, or overdue",
    "volumengewichtet": "volume weighted",
    "Überfällig": "Overdue",
    "Kundenkonto": "Customer account",
    "Nur Lesen": "Read only",
    "Rollenberechtigungen aktiv": "Role permissions active",
    "Nicht konfiguriert": "Not configured",
    "Zur Provider-Konsole": "Back to provider console",
    "Öffentliche Demo - read-only": "Public demo - read only",
    "Änderungen werden nicht gespeichert. Nutze eine eigene DMARQ-Installation, um echte Einstellungen zu ändern.": "Changes are not saved. Use your own DMARQ installation to change real settings.",
}


CATALOGS: Dict[str, Dict[str, str]] = {"en": EN_TRANSLATIONS, "de": DE_TRANSLATIONS}


def normalize_locale(value: Optional[str], default: str = "en") -> str:
    """Normalize locale variants and fall back to a supported language."""
    candidate = (value or "").strip().lower().replace("_", "-")
    if candidate.startswith("de"):
        return "de"
    if candidate.startswith("en"):
        return "en"
    return "de" if (default or "").lower().startswith("de") else "en"


def resolve_request_locale(request: Request, default: str = "en") -> str:
    """Resolve explicit URL/cookie choices before the deployment default."""
    query_locale = request.query_params.get("lang") if "query_string" in request.scope else None
    explicit = query_locale or request.cookies.get(LOCALE_COOKIE)
    return normalize_locale(explicit, default=default)


def translate(message: str, locale: str) -> str:
    """Translate one source-language message with an English fallback."""
    return CATALOGS.get(normalize_locale(locale), {}).get(message, message)


def catalog_for_locale(locale: str) -> Dict[str, str]:
    """Return the immutable source catalog selected for a browser request."""
    return CATALOGS.get(normalize_locale(locale), {})


def template_locale_context(request: Request, default: str = "en") -> dict:
    """Build the locale variables injected into every Jinja template."""
    locale = resolve_request_locale(request, default=default)
    return {
        "locale": locale,
        "supported_locales": SUPPORTED_LOCALES,
        "_": lambda message: translate(message, locale),
    }
